name: Add commit messages to PR body
on:
  pull_request:
    types: [opened, reopened]

jobs:
  add_commit_messages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Add commit messages to PR body
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          COMMIT_MESSAGES=$(git log --format="%s" HEAD...HEAD~1)
          PAYLOAD=$(echo '{}' | jq --arg body "$(jq -Rs . <<< "$COMMIT_MESSAGES")" '.body = $body')
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -X PATCH \
            -d "$PAYLOAD" \
            "https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER"